### PR TITLE
Results of Toronto Brain Hackathon

### PR DESCRIPTION
**Pull request by kgeier**
Hi Fahd,

Not sure if Derick told you but a couple of us (Jinting Zhang, Giulia Baracchini, and I) were making some subtle updates for the RecommendR shiny app. 

We're all fairly novice so we didn't accomplish much but it's at least an improvement. 

Note, the names of the two scripts have changed (app.R to App.R and helpers.R to Helpers2.R) so if you like what we've changed you'll have to use those to put a new version online.

Thanks and let me know if you have questions. My email is kirkgeier@gmail.com if you need it.

### CODE REVIEW

**Comment by fahd09** [comment]
Hi Kgeier,

Thanks for submitting this! I have merged the pull request to the repo now.

**Comment by kgeier** [comment]
Hi Fahd,

Thanks! What's the next step for how to get the new version to show up at
this link? https://neurosanity.shinyapps.io/NeurosynthRecommendR/

Let me know if I can help in any way

**Comment by fahd09** [comment]
I will test if things work properly on my machine first, and then I will upload it to the shiny app. I will get this done as soon as this weekend.

**Comment by kgeier** [comment]
Okay cool

Thanks!

**Pull request merged**
